[tox]
isolated_build = True
envlist = py{39,310,311,312}, full, data, manifest, check-formatting, lint, mypy

[testenv]
skip_install = true
allowlist_externals = poetry
commands_pre =
    poetry install --no-root --sync
commands =
    poetry run pytest {posargs:tests/}

[testenv:full]
skip_install = true
allowlist_externals = poetry
commands_pre =
    poetry install --no-root --sync --with test,dev
commands =
    poetry run pytest {posargs:tests/}

[testenv:data]
skip_install = true
allowlist_externals = poetry
commands_pre =
    poetry install --no-root --sync --with data
commands =
    poetry run pytest {posargs:tests/}

[testenv:manifest]
skip_install = true
allowlist_externals = poetry
commands_pre =
    poetry install --no-root --sync --with dev
commands =
    poetry run check-manifest

[testenv:check-formatting]
skip_install = true
allowlist_externals = poetry
commands_pre =
    poetry install --no-root --sync --with dev
commands =
    poetry run black --check .

[testenv:format]
skip_install = true
allowlist_externals = poetry
commands_pre =
    poetry install --no-root --sync --with dev
commands =
    poetry run black .

[testenv:lint]
skip_install = true
allowlist_externals = poetry
commands_pre =
    poetry install --no-root --sync --with dev
commands =
    poetry run ruff check .

[testenv:mypy]
skip_install = true
allowlist_externals = poetry
commands_pre =
    poetry install --no-root --sync --with dev
commands =
    poetry run mypy basic_pitch

[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
addopts = --doctest-modules

[flake8]
max-line-length = 120
ignore = E203, W503
exclude = .git,__pycache__,build,dist,*.egg-info
